#!/bin/sh
### BEGIN INIT INFO
# Provides:          lxiserver
# Required-Start:    lighttpd
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     
# Default-Stop:      
# Short-Description: Start up the the Lenovo XClarity Integrator server daemon
# Description:       Lenovo XClarity Integrator server works with lighttpd 
#                    together to handle http request(py).
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/python
NAME=lxiserver
DESC="Lenovo XClarity Integrator server"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
DAEMON_OPTS=/opt/lenovo/UnifiedService/webroot/bin/ServerStart.pyc

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" $NAME
        if ! start-stop-daemon --start --oknodo --background --quiet \
            --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        then
            log_end_msg 1
        else        
            log_end_msg 0
            ps -fe | grep -i "python.*$DAEMON_OPTS" | head -n1 | awk '{print $2}' > $PIDFILE
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" $NAME
        if start-stop-daemon --stop --retry 30 --oknodo --quiet \
            --pidfile $PIDFILE --exec $DAEMON
        then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0
